apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - obridge-configmap.yaml
  - ludoc-config.yaml
  - ludoc-agent.yaml
  - ludoc-pvc.yaml
  - patient-records-configmap.yaml
  - patient-records-deployment.yaml
